// Icon registry — generated by scripts/migrate/generate-icons.mjs.
//
// The single-file app loaded the whole lucide UMD bundle and let
// `lucide.createIcons()` swap every `<i data-lucide="...">` for an SVG.
// React components should not have their DOM swapped behind their back, so:
//
//   - markup that React renders uses <Icon name="..." /> (below)
//   - HTML strings the engine builds with innerHTML keep `data-lucide` and
//     call createIcons(root), which only touches engine-owned DOM
//
// The registry lists exactly the 85 icons this app uses, so the bundle
// ships those and nothing else.
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import {
  Activity,
  ArrowUpNarrowWide,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleHelp,
  Code2,
  Combine,
  Compass,
  Copy,
  CopyPlus,
  Crosshair,
  Dices,
  Download,
  Droplets,
  Edit3,
  Eraser,
  FileCode,
  FileUp,
  Film,
  GitCommit,
  GitMerge,
  Globe,
  Globe2,
  GraduationCap,
  Hand,
  HeartHandshake,
  HelpCircle,
  Image,
  Info,
  Keyboard,
  Landmark,
  Layers,
  Layers3,
  Lightbulb,
  Lock,
  Map,
  MapPin,
  MapPinned,
  Maximize,
  Maximize2,
  Microscope,
  Minus,
  Moon,
  MoonStar,
  Mountain,
  MousePointerClick,
  Move,
  PaintBucket,
  Palette,
  PenTool,
  PencilRuler,
  Pentagon,
  Pipette,
  PlusCircle,
  Redo2,
  Scan,
  ScanLine,
  ScanSearch,
  Scissors,
  ScissorsLineDashed,
  Search,
  Shapes,
  Share,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Split,
  Square,
  SquareDashedBottom,
  Sun,
  SunMedium,
  Tag,
  Target,
  Trash2,
  Undo2,
  Unlock,
  UploadCloud,
  Wand2,
  WandSparkles,
  Waves,
  X,
  Zap,
} from 'lucide-react';

export const ICONS = {
  "activity": Activity,
  "arrow-up-narrow-wide": ArrowUpNarrowWide,
  "check": Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "circle-help": CircleHelp,
  "code-2": Code2,
  "combine": Combine,
  "compass": Compass,
  "copy": Copy,
  "copy-plus": CopyPlus,
  "crosshair": Crosshair,
  "dices": Dices,
  "download": Download,
  "droplets": Droplets,
  "edit-3": Edit3,
  "eraser": Eraser,
  "file-code": FileCode,
  "file-up": FileUp,
  "film": Film,
  "git-commit": GitCommit,
  "git-merge": GitMerge,
  "globe": Globe,
  "globe-2": Globe2,
  "graduation-cap": GraduationCap,
  "hand": Hand,
  "heart-handshake": HeartHandshake,
  "help-circle": HelpCircle,
  "image": Image,
  "info": Info,
  "keyboard": Keyboard,
  "landmark": Landmark,
  "layers": Layers,
  "layers-3": Layers3,
  "lightbulb": Lightbulb,
  "lock": Lock,
  "map": Map,
  "map-pin": MapPin,
  "map-pinned": MapPinned,
  "maximize": Maximize,
  "maximize-2": Maximize2,
  "microscope": Microscope,
  "minus": Minus,
  "moon": Moon,
  "moon-star": MoonStar,
  "mountain": Mountain,
  "mouse-pointer-click": MousePointerClick,
  "move": Move,
  "paint-bucket": PaintBucket,
  "palette": Palette,
  "pen-tool": PenTool,
  "pencil-ruler": PencilRuler,
  "pentagon": Pentagon,
  "pipette": Pipette,
  "plus-circle": PlusCircle,
  "redo-2": Redo2,
  "scan": Scan,
  "scan-line": ScanLine,
  "scan-search": ScanSearch,
  "scissors": Scissors,
  "scissors-line-dashed": ScissorsLineDashed,
  "search": Search,
  "shapes": Shapes,
  "share": Share,
  "shield-check": ShieldCheck,
  "sliders-horizontal": SlidersHorizontal,
  "sparkles": Sparkles,
  "split": Split,
  "square": Square,
  "square-dashed-bottom": SquareDashedBottom,
  "sun": Sun,
  "sun-medium": SunMedium,
  "tag": Tag,
  "target": Target,
  "trash-2": Trash2,
  "undo-2": Undo2,
  "unlock": Unlock,
  "upload-cloud": UploadCloud,
  "wand-2": Wand2,
  "wand-sparkles": WandSparkles,
  "waves": Waves,
  "x": X,
  "zap": Zap,
};

const warned = new Set();
export function getIcon(name) {
  const component = ICONS[name];
  if (!component && !warned.has(name)) {
    warned.add(name);
    console.warn(`[icons] unknown icon '${name}' — add it to src/lib/icons.js`);
  }
  return component || null;
}

/** React component replacement for `<i data-lucide="name">`. */
export function Icon({ name, className, ...rest }) {
  const component = getIcon(name);
  if (!component) return null;
  return createElement(component, { className, ...rest });
}

/** SVG markup string, for engine code that writes innerHTML. */
export function iconSvg(name, attrs = {}) {
  const component = getIcon(name);
  if (!component) return '';
  return renderToStaticMarkup(createElement(component, attrs));
}

/**
 * Drop-in replacement for lucide.createIcons(), scoped to a subtree the
 * engine owns. Never call this on React-rendered markup.
 */
export function createIcons(root = document.body) {
  if (!root) return;
  const nodes = root.matches?.('i[data-lucide]') ? [root] : [...root.querySelectorAll('i[data-lucide]')];
  for (const el of nodes) {
    const attrs = {};
    for (const attr of el.attributes) {
      if (attr.name === 'data-lucide') continue;
      attrs[attr.name === 'class' ? 'className' : attr.name] = attr.value;
    }
    const markup = iconSvg(el.getAttribute('data-lucide'), attrs);
    if (!markup) continue;
    const holder = document.createElement('div');
    holder.innerHTML = markup;
    const svg = holder.firstElementChild;
    if (svg) el.replaceWith(svg);
  }
}

export default { createIcons, iconSvg, getIcon, ICONS };
