// Every engine function the UI can invoke — generated by
// scripts/migrate/generate-actions.mjs.
//
// Markup used to call these through inline `onclick` attributes, which only
// works for real globals. This barrel is what JSX handlers reach for instead,
// so components stay free of engine imports and the engine stays free of React.
import {
  setBaseMap,
  toggleBorderOverlay,
} from './baseMaps.js';
import {
  applyBorderDetail,
  randomizeBorderSeed,
  undoBorderDetail,
} from './borderDetail.js';
import {
  boostCoastDetail,
  fetchFastCoastTiles,
  refineSelectionWithTilesCoast,
  simplifySelectedCoast,
  snapSelectionToOsmCoast,
} from './coastTiles.js';
import {
  randomizeSelectedColor,
} from './colors.js';
import {
  deleteSelectedLoaded,
  ensureCountryIndex,
  onCountrySearchInput,
  onLoadModeChange,
  resetCountryIndex,
  toggleDeleteMode,
  toggleSelectOnMapMode,
} from './countries.js';
import {
  curveAllEdges,
  setCurveAmount,
  setDrawCurveDepth,
  setDrawCurveEnabled,
  straightenAllEdges,
  toggleCurveEdgeMode,
} from './curves.js';
import {
  deleteSelectedOrLast,
  setDrawMode,
  toggleEditMode,
} from './drawTools.js';
import {
  downloadAlightMotionXML,
} from './exporters/alightMotion.js';
import {
  downloadXML,
} from './exporters/kml.js';
import {
  downloadTransparentPNG,
} from './exporters/png.js';
import {
  downloadSVG,
} from './exporters/svg.js';
import {
  importGeoJSONFile,
} from './geojsonLoader.js';
import {
  undoGeorefDetection,
} from './georef.js';
import {
  redoHistory,
  undoHistory,
} from './history.js';
import {
  setCoastlineLevel,
} from './landmass.js';
import {
  applySingleColorToAll,
  clearMergeSelection,
  cutSeaFromPolygon,
  executeMerge,
  mergeAllLoadedUnits,
  mergeAllTouching,
  removeLoadedCountries,
  toggleAutoSeaCut,
  toggleMergeMode,
  triggerCutSeaNow,
} from './merge.js';
import {
  addOsmCoastAsShape,
  clearOsmCoastline,
  fetchOsmCoastlineAction,
} from './osmCoastline.js';
import {
  adjustScaleRelative,
  applyScaleSlider,
  autoPlaceOverlay,
  handleImageUpload,
  nudgeImage,
  recenterImageToMap,
  removeReferenceImage,
  saveNudgeConfig,
  setImageOpacity,
  toggleAspectRatioLock,
  toggleImageHandles,
} from './overlayImage.js';
import {
  copyGeoJSONToClipboard,
  downloadGeoJSON,
  duplicateSelectedShape,
  fitAllShapes,
  toggleShortcutSheet,
  zoomToSelection,
} from './quickTools.js';
import {
  addDetectedCoastAsShapes,
  autoDetectSeaColor,
  clearDetectedCoastPreview,
  detectCoastlineFromSeaColor,
  runGeorefDetection,
  setSeaColor,
  setSeaDetectEnabled,
  setSeaTolerance,
  toggleSeaPickFromOverlay,
} from './seaDetect.js';
import {
  cancelSplitMode,
  startSplitMode,
} from './split.js';
import {
  openStyleDrawerForActive,
  updateActiveFeatureProp,
  updateActiveStyle,
} from './styleInspector.js';
import {
  bakePolygonsIntoMap,
  unbakePolygons,
} from './tileBake.js';
import {
  endTutorial,
  expandTutorial,
  locateUser,
  minimizeTutorial,
  startTutorial,
  tutorialCTA,
  tutorialNext,
  tutorialPrev,
} from './tutorial.js';
import {
  closeDrawers,
  toggleDrawer,
} from './uiHelpers.js';

const actions = {
  addDetectedCoastAsShapes,
  addOsmCoastAsShape,
  adjustScaleRelative,
  applyBorderDetail,
  applyScaleSlider,
  applySingleColorToAll,
  autoDetectSeaColor,
  autoPlaceOverlay,
  bakePolygonsIntoMap,
  boostCoastDetail,
  cancelSplitMode,
  clearDetectedCoastPreview,
  clearMergeSelection,
  clearOsmCoastline,
  closeDrawers,
  copyGeoJSONToClipboard,
  curveAllEdges,
  cutSeaFromPolygon,
  deleteSelectedLoaded,
  deleteSelectedOrLast,
  detectCoastlineFromSeaColor,
  downloadAlightMotionXML,
  downloadGeoJSON,
  downloadSVG,
  downloadTransparentPNG,
  downloadXML,
  duplicateSelectedShape,
  endTutorial,
  ensureCountryIndex,
  executeMerge,
  expandTutorial,
  fetchFastCoastTiles,
  fetchOsmCoastlineAction,
  fitAllShapes,
  handleImageUpload,
  importGeoJSONFile,
  locateUser,
  mergeAllLoadedUnits,
  mergeAllTouching,
  minimizeTutorial,
  nudgeImage,
  onCountrySearchInput,
  onLoadModeChange,
  openStyleDrawerForActive,
  randomizeBorderSeed,
  randomizeSelectedColor,
  recenterImageToMap,
  redoHistory,
  refineSelectionWithTilesCoast,
  removeLoadedCountries,
  removeReferenceImage,
  resetCountryIndex,
  runGeorefDetection,
  saveNudgeConfig,
  setBaseMap,
  setCoastlineLevel,
  setCurveAmount,
  setDrawCurveDepth,
  setDrawCurveEnabled,
  setDrawMode,
  setImageOpacity,
  setSeaColor,
  setSeaDetectEnabled,
  setSeaTolerance,
  simplifySelectedCoast,
  snapSelectionToOsmCoast,
  startSplitMode,
  startTutorial,
  straightenAllEdges,
  toggleAspectRatioLock,
  toggleAutoSeaCut,
  toggleBorderOverlay,
  toggleCurveEdgeMode,
  toggleDeleteMode,
  toggleDrawer,
  toggleEditMode,
  toggleImageHandles,
  toggleMergeMode,
  toggleSeaPickFromOverlay,
  toggleSelectOnMapMode,
  toggleShortcutSheet,
  triggerCutSeaNow,
  tutorialCTA,
  tutorialNext,
  tutorialPrev,
  unbakePolygons,
  undoBorderDetail,
  undoGeorefDetection,
  undoHistory,
  updateActiveFeatureProp,
  updateActiveStyle,
  zoomToSelection,
};

export default actions;
