// Shared mutable application state.
//
// The original single-file app kept ~90 top-level `let` bindings in one script
// scope. They now live on a single object behind a Proxy, which lets React
// subscribe to changes (see src/store/useAppState.js) without the engine
// having to announce anything — assigning `S.foo = x` notifies on its own.
import { createStore } from '../store/createStore.js';
import { CURVE_DEFAULT_AMOUNT } from './constants.js';

const initialState = {
  map: undefined,
  drawnItems: undefined,
  autoCutSeaEnabled: false,
  baseTileLayers: {},
  borderOverlays: {},
  activeBaseKey: 'dark',
  activeSelectedLayer: null,
  landFeaturesList: [],
  colorSeq: 0,
  heavyLibsPromise: null,
  landLoadPromise: null,
  pendingLandLevel: null,
  currentLandLevel: 'medium',
  landCache: {},
  roughenSnapshot: null,
  roughenSeed: Math.floor(Math.random() * 1e9),
  curveMode: false,
  curveModeLayer: null,
  curveHandles: [],
  drawCurveEnabled: false,
  drawCurveAmount: CURVE_DEFAULT_AMOUNT,
  drawGhostLayer: null,
  drawGhostWorking: null,
  bakedLayer: null,
  bakedActive: false,
  savedShapeStyles: null,
  nudgeAmount: 8,
  nudgeUnit: 'percent',
  nudgeKeysEnabled: true,
  splitModeActive: false,
  countryLayers: [],
  countryLayerById: {},
  countriesIndexCache: {},
  countryIndexPromises: {},
  countrySearchTimer: null,
  adm1IndexCache: null,
  adm1IndexPromise: null,
  numToAlpha3: null,
  isoTablePromise: null,
  selectOnMapMode: false,
  deleteMode: false,
  mergeMode: false,
  mergeSelection: [],
  referenceImageLayer: null,
  referenceImageRawUrl: null,
  imageNaturalAspectRatio: 1.0,
  imageCenter: null,
  overlayPxW: 0,
  overlayPxH: 0,
  overlayBasePxW: 0,
  overlayBasePxH: 0,
  scaleW: 1.0,
  scaleH: 1.0,
  keepAspectRatioLocked: true,
  centerMoveMarker: null,
  cornerResizeMarker: null,
  areImageHandlesLocked: false,
  worldBorderLines: [],
  bordersChanPromise: null,
  georefBusy: false,
  lastGeorefSnapshot: null,
  osmCoastLines: [],
  osmPreviewLayer: null,
  osmFetchBusy: false,
  osmTileUrlPattern: 'https://tiles.openfreemap.org/planet/{z}/{x}/{y}.pbf',
  osmTilesOcean: [],
  osmTileZoomUsed: 0,
  seaColorHex: '#a5bfdd',
  seaDetectEnabled: true,
  seaTolerance: 60,
  seaPickMode: false,
  overlayPixelCache: null,
  detectedCoastPolylines: null,
  detectedCoastPreviewLayer: null,
  seaPickHintLayers: [],
  vertexMarkers: [],
  handleArmLayer: null,
  vertexDragFlag: false,
  curveRebuildQueued: false,
  curveSettleTimer: null,
  bakeRefreshQueued: false,
  bakeSoonTimer: null,
  maplibreLibPromise: null,
  statsCoalesceTimer: null,
  lastHeavyStatsMs: 0,
  heavyStatsCount: 0,
  historyStack: [],
  historyIndex: -1,
  historyRestoring: false,
  lastHistorySignature: '',
  tutorialIndex: 0,
  tourBaseCycle: 0,
};

export const { store: S, subscribe, getVersion } = createStore(initialState);
