// Regenerates src/engine/actions.js — the barrel of every engine function the
// UI can call.
//
// Run after split-engine.mjs (which writes .migrate/module-map.json) and
// generate-jsx.mjs (which writes .migrate/handlers-used.json).
import fs from 'node:fs';

const used = JSON.parse(fs.readFileSync('.migrate/handlers-used.json', 'utf8'));
const map = JSON.parse(fs.readFileSync('.migrate/module-map.json', 'utf8'));

const owner = new Map();
for (const [mod, names] of Object.entries(map.modules)) {
  for (const n of names) if (!owner.has(n)) owner.set(n, mod);
}

const groups = new Map();
const orphaned = [];
for (const name of used) {
  const mod = owner.get(name);
  if (!mod) { orphaned.push(name); continue; }
  if (!groups.has(mod)) groups.set(mod, []);
  groups.get(mod).push(name);
}
if (orphaned.length) {
  throw new Error(`no owning module for: ${orphaned.join(', ')}`);
}

const imports = [...groups]
  .sort()
  .map(([mod, names]) => {
    const dest = mod === '@util' ? '../lib/util.js' : `./${mod}.js`;
    return `import {\n${names.sort().map((n) => '  ' + n + ',').join('\n')}\n} from '${dest}';`;
  });

const all = [...used].sort();
const out = `// Every engine function the UI can invoke — generated by
// scripts/migrate/generate-actions.mjs.
//
// Markup used to call these through inline \`onclick\` attributes, which only
// works for real globals. This barrel is what JSX handlers reach for instead,
// so components stay free of engine imports and the engine stays free of React.
${imports.join('\n')}

const actions = {
${all.map((n) => '  ' + n + ',').join('\n')}
};

export default actions;
`;

fs.writeFileSync('src/engine/actions.js', out);
console.log(`wrote src/engine/actions.js — ${all.length} actions from ${groups.size} modules`);
