// Regenerates src/lib/icons.js — the registry of every icon this app uses.
//
// Names are collected from the original markup (`data-lucide`) and from the
// HTML strings the engine builds at runtime (marker labels, tutorial steps).
// Listing them explicitly keeps the bundle to exactly the icons in use instead
// of pulling in all ~1,500 that lucide-react exports.
import fs from 'node:fs';

const names = new Set();
const body = fs.readFileSync('.migrate/body.html', 'utf8');
const engine = fs.readFileSync('.migrate/engine.js', 'utf8');

for (const m of body.matchAll(/data-lucide="([^"]+)"/g)) names.add(m[1]);
for (const m of engine.matchAll(/data-lucide=\\?"([a-z0-9-]+)\\?"/g)) names.add(m[1]);
for (const m of engine.matchAll(/icon: '([a-z0-9-]+)'/g)) names.add(m[1]);

const sorted = [...names].sort();
const pascal = (n) => n.split('-').map((p) => p[0].toUpperCase() + p.slice(1)).join('');

const out = `// Icon registry — generated by scripts/migrate/generate-icons.mjs.
//
// The single-file app loaded the whole lucide UMD bundle and let
// \`lucide.createIcons()\` swap every \`<i data-lucide="...">\` for an SVG.
// React components should not have their DOM swapped behind their back, so:
//
//   - markup that React renders uses <Icon name="..." /> (below)
//   - HTML strings the engine builds with innerHTML keep \`data-lucide\` and
//     call createIcons(root), which only touches engine-owned DOM
//
// The registry lists exactly the ${sorted.length} icons this app uses, so the bundle
// ships those and nothing else.
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import {
${sorted.map((n) => '  ' + pascal(n) + ',').join('\n')}
} from 'lucide-react';

export const ICONS = {
${sorted.map((n) => '  ' + JSON.stringify(n) + ': ' + pascal(n) + ',').join('\n')}
};

const warned = new Set();
export function getIcon(name) {
  const component = ICONS[name];
  if (!component && !warned.has(name)) {
    warned.add(name);
    console.warn(\`[icons] unknown icon '\${name}' — add it to src/lib/icons.js\`);
  }
  return component || null;
}

/** React component replacement for \`<i data-lucide="name">\`. */
export function Icon({ name, className, ...rest }) {
  const component = getIcon(name);
  if (!component) return null;
  return createElement(component, { className, ...rest });
}

/** SVG markup string, for engine code that writes innerHTML. */
export function iconSvg(name, attrs = {}) {
  const component = getIcon(name);
  if (!component) return '';
  return renderToStaticMarkup(createElement(component, attrs));
}

/**
 * Drop-in replacement for lucide.createIcons(), scoped to a subtree the
 * engine owns. Never call this on React-rendered markup.
 */
export function createIcons(root = document.body) {
  if (!root) return;
  const nodes = root.matches?.('i[data-lucide]') ? [root] : [...root.querySelectorAll('i[data-lucide]')];
  for (const el of nodes) {
    const attrs = {};
    for (const attr of el.attributes) {
      if (attr.name === 'data-lucide') continue;
      attrs[attr.name === 'class' ? 'className' : attr.name] = attr.value;
    }
    const markup = iconSvg(el.getAttribute('data-lucide'), attrs);
    if (!markup) continue;
    const holder = document.createElement('div');
    holder.innerHTML = markup;
    const svg = holder.firstElementChild;
    if (svg) el.replaceWith(svg);
  }
}

export default { createIcons, iconSvg, getIcon, ICONS };
`;

fs.mkdirSync('src/lib', { recursive: true });
fs.writeFileSync('src/lib/icons.js', out);
console.log(`wrote src/lib/icons.js with ${sorted.length} icons`);
